# Event codes are found at /usr/include/linux/input-event-codes.h
# Run `evtest` to follow the event names of keypresses on the controller
[remap]
BTN_SOUTH = ["BTN_LEFT"] # A -> LClick
BTN_NORTH = ["BTN_RIGHT"] # X -> RClick
BTN_TL = ["BTN_MIDDLE"] # LT -> MClick

BTN_WEST = ["BTN_EXTRA"] # Y -> forward
BTN_EAST = ["BTN_SIDE"] # B -> back

# D-pad to arrows
BTN_DPAD_UP = ["KEY_UP"]
BTN_DPAD_DOWN = ["KEY_DOWN"]
BTN_DPAD_LEFT = ["KEY_LEFT"]
BTN_DPAD_RIGHT = ["KEY_RIGHT"]

[commands]
# Select button to toggle launcher
BTN_SELECT = ["qs -c noctalia-shell ipc call launcher toggle"]
# Start button to toggle session menu
BTN_START = ["qs -c noctalia-shell ipc call sessionMenu toggle"]
# X-Box Button to disable KM mode
BTN_MODE = ["/home/yori/bin/start-makima.sh 0"]

[settings]
SCROLL_SPEED = "5"
SCROLL_ACCEL = "0.1"
INVERT_SCROLL_AXIS = "true"
CURSOR_SPEED = "5"
CURSOR_ACCEL = "0.1"
# Left Stick for mouse movement
LSTICK = "cursor"
LSTICK_SENSITIVITY = "10" 
LSTICK_DEADZONE = "10"
# Disabling Right Stick if not used, or set to "scroll"
RSTICK = "scroll"
RSTICK_SENSITIVITY = "10" 
RSTICK_DEADZONE = "10"
# Standard for X-input/Xbox controllers
16_BIT_AXIS = "true"
GRAB_DEVICE = "true"
