[mgr]
show_hidden = true
sort_by = "natural"
sort_translit = true
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_symlink = true
mouse_events =  ["scroll","click"]


[opener]
edit = [
    { run = '${EDITOR} "$@"', block = true, desc = "Edit File" }
]
run = [
    {run = 'exec "$@"', block = true, desc = "Run bash..."}
]
edit_folder = [
    { run = 'cd "$1" && ${EDITOR} .', block = true, desc = "Open in NeoVim"}
]

[open]
rules = [
    { mime = "folder/local", use = "edit_folder" },
    { name = "*.sh", use = ["edit", "run"] },
    { mime = "text/shellscript", use = ["edit", "run"] },
    { mime = "text/*", use = "edit" },
    { mime = "*", use = "edit" }
]
